### PR TITLE
Supported editors

### PR DESCRIPTION
**Pull request by anteriovieira**
I do not know if the list is correct, but it would be nice to have the list in the documentation.

### CODE REVIEW

**Comment by anteriovieira** [comment]
cc @yyx990803

**Comment by yyx990803** [comment]
I don't think the list is accurate, please update it per https://github.com/yyx990803/launch-editor/tree/master/packages/launch-editor/editor-info

**Comment by anteriovieira** [comment]
@yyx990803  updated

| Value | Editor | Linux | Windows | OSX |
|--------|------|:------:|:------:|:------:|
| `appcode` | [AppCode](https://www.jetbrains.com/objc/) |  |  |●|
| `atom` | [Atom](https://atom.io/) |●|●|●|
| `atom-beta` | [Atom Beta](https://atom.io/beta) |  |  |●|
| `brackets` | [Brackets](http://brackets.io/) |●|●|●|
| `clion` | [Clion](https://www.jetbrains.com/clion/) |  |●|●|
| `code` | [Visual Studio Code](https://code.visualstudio.com/) |●|●|●|
| `code-insiders` | [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/) |●|●|●|
| `emacs` | [Emacs](https://www.gnu.org/software/emacs/) |●| | |
| `idea` | [IDEA](https://www.jetbrains.com/idea/) |●|●|●|
| `notepad++` | [Notepad++](https://notepad-plus-plus.org/download/v7.5.4.html) | |●| |
| `pycharm` | [PyCharm](https://www.jetbrains.com/pycharm/) |●|●|●|
| `phpstorm` | [PhpStorm](https://www.jetbrains.com/phpstorm/) |●|●|●|
| `rubymine` | [RubyMine](https://www.jetbrains.com/ruby/) |●|●|●|
| `sublime` | [Sublime Text](https://www.sublimetext.com/) |●|●|●|
| `vim` | [Vim](http://www.vim.org/) |●| | |
| `visualstudio` | [Visual Studio](https://www.visualstudio.com/vs/) | | |●|
| `webstorm` | [WebStorm](https://www.jetbrains.com/webstorm/) |●|●|●|

**Comment by yyx990803** [comment]
Thanks!

**Pull request merged**
